### ISSUE TITLE
Including licenses in the distribution?

### ISSUE THREAD

**Issue by bollwyvl** [phith0n/pyduktape2#5]
Hello! Thanks for this tool.

I'm looking to package this for conda (via conda-forge) as it has become an optional dependency of pyshacl, and noticed a few things about the distribution:
- the AGPL is not in the repo, and therefore not in the sdist/wheel!
- the duktape source is included without attribution or license

Really just pasting the text in and adding it to MANIFEST.in and adding `include_package_data` to `setup.*` would be sufficient to get compliant: I'd be happy to PR these, as well.

Thanks again!

**Comment by phith0n** [comment]
Hi Nicholas, 

Thanks for your suggestion, don't hesitate to pull request for this project please.

**Comment by bollwyvl** [comment]
Lovely! :heart: 

As soon as a new `.tar.gz` release is out on PyPI, I'll see about getting it built for `conda-forge`, which will help close out https://github.com/conda-forge/pyshacl-feedstock/issues/22

Thanks again!

**Comment by phith0n** [comment]
Sure, I'm handling the errors on Github Actions. Will publish after the issue is resolved.
